n_features: 25
features_set_name: "025"

features_list: 
  - 'acc_x_st_mean' 
  - 'acc_y_st_mean' 
  - 'acc_z_st_mean' 
  - 'pitch_mean' 
  - 'roll_mean'  
  - 'VeDBA_mean' 
  - 'VeDBA_s_mean'
  - 'acc_x_PDBA_mean'
  - 'acc_y_PDBA_mean'
  - 'acc_z_PDBA_mean'
  - 'x_ratio_VeDBA_to_PDBA_mean'
  - 'y_ratio_VeDBA_to_PDBA_mean'
  - 'z_ratio_VeDBA_to_PDBA_mean'
  - 'acc_x_main_freq_1' 
  - 'acc_x_main_psd_1'
  - 'acc_x_main_freq_2'
  - 'acc_x_main_psd_2' 
  - 'acc_y_main_freq_1' 
  - 'acc_y_main_psd_1' 
  - 'acc_y_main_freq_2'  
  - 'acc_y_main_psd_2' 
  - 'acc_z_main_freq_1'
  - 'acc_z_main_psd_1'
  - 'acc_z_main_freq_2'
  - 'acc_z_main_psd_2'