n_features: 78
features_set_name: "078"

features_list:
  - 'acc_x_mean' 
  - 'acc_y_mean' 
  - 'acc_z_mean' 
  - 'acc_x_var' 
  - 'acc_y_var' 
  - 'acc_z_var' 
  - 'acc_x_std' 
  - 'acc_y_std' 
  - 'acc_z_std' 
  - 'acc_x_cv' 
  - 'acc_y_cv' 
  - 'acc_z_cv'
  - 'acc_x_skew' 
  - 'acc_y_skew' 
  - 'acc_z_skew'
  - 'acc_x_kurtosis' 
  - 'acc_y_kurtosis' 
  - 'acc_z_kurtosis' 
  - 'acc_x_max' 
  - 'acc_y_max' 
  - 'acc_z_max' 
  - 'acc_x_min' 
  - 'acc_y_min' 
  - 'acc_z_min' 
  - 'acc_x_range' 
  - 'acc_y_range' 
  - 'acc_z_range'
  - 'acc_x_q25' 
  - 'acc_y_q25' 
  - 'acc_z_q25' 
  - 'acc_x_q50' 
  - 'acc_y_q50' 
  - 'acc_z_q50'
  - 'acc_x_q75' 
  - 'acc_y_q75' 
  - 'acc_z_q75' 
  - 'acc_x_norm'
  - 'acc_y_norm'
  - 'acc_z_norm'
  - 'cov_xy' 
  - 'cov_yz' 
  - 'cov_zx' 
  - 'corr_xy' 
  - 'corr_yz' 
  - 'corr_zx'
  - 'diff_xy_mean' 
  - 'diff_yz_mean' 
  - 'diff_zx_mean' 
  - 'diff_xy_std' 
  - 'diff_yz_std' 
  - 'diff_zx_std' 
  - 'acc_x_st_var' 
  - 'acc_y_st_var' 
  - 'acc_z_st_var' 
  - 'pitch_mean' 
  - 'roll_mean' 
  - 'acc_x_dy_mean' 
  - 'acc_y_dy_mean' 
  - 'acc_z_dy_mean'
  - 'acc_x_dy_var' 
  - 'acc_y_dy_var' 
  - 'acc_z_dy_var'
  - 'acc_x_dy_max' 
  - 'acc_y_dy_max'
  - 'acc_z_dy_max'
  - 'ODBA_mean' 
  - 'acc_x_dcp_mean' 
  - 'acc_y_dcp_mean' 
  - 'acc_z_dcp_mean'
  - 'acc_x_dcp_std' 
  - 'acc_y_dcp_std' 
  - 'acc_z_dcp_std'
  - 'acc_x_main_freq_1'
  - 'acc_x_main_amp_1' 
  - 'acc_y_main_freq_1' 
  - 'acc_y_main_amp_1'
  - 'acc_z_main_freq_1'
  - 'acc_z_main_amp_1'