defaults:
  - path
  - _self_
  - dataset: om
  - model: xgboost # xgboost, lightgbm
  - features: "119-features" # "025-features", "078-features", "119-features"
  - override hydra/job_logging: console_and_file
  
hydra:
  run:
    dir: ${path.log.rootdir}
  job:
    chdir: true

issue: "I03"
ex: "ex-d90"
debug: false
seed: 0 # random seed
k8s: false

representative_sample: "last" 
# always last for dl-wabc (all labels in a window are the same)

metadata:
  approach: 'ml'
  task: 'loiocv'

train:
  cuda: 0
  train_val_split: true
  train_data_ratio: 0.8 # validation data used only for early stopping
  under_sampling: true # under-sampling majority class before SMOTE
  smote: true # Synthetic Minority Oversampling TEchnique
  smote_k_neighbors: 3 # default=5
  smote_dir_name: "smote-true" # "smote-false"
  n_estimators: 10000
  learning_rate: 0.01
  early_stopping_rounds: 10
  max_depth: 6

sub0: "${issue}/${ex}"
sub1: "${dataset.species}-${dataset.window_size}"
sub2: "${model.model_name}"
sub3: "" # override sub3 when running models using k8s
# sub3: "${representative_sample}" # override sub3 when running models using k8s
sub4: "${model.model_name}-feats-${features.features_set_name}-${train.smote_dir_name}"
sub5: "seed${seed}"
sub_root_dir: "${sub0}/${sub1}/${sub2}/${sub3}/${sub4}/${sub5}"